#ifndef __WEB_H
#define __WEB_H
const uint8_t web[]={
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">"
"<html xmlns=\"http://www.w3.org/1999/xhtml\">"
"<head>"
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />"
"<title>Untitled Document</title>"
"</head>"
"<body bgcolor=\"gray\">"
"<center>"
"<font size=\"+6\"> MINH HA GROUP</font><br /><br />"
"<font size=\"+4\"> DEMO ETHERNET V1.0</font><br /><br />"
"<img src=\"http://banlinhkien.vn/images/Logo%20ban%20linhkien.png\" /><br /><br>"
"<form method=\"post\" action=\"\">"
"<table border=\"1\">"
"<tr>"
"<td>LED 1: <br />"
"<input type=\"radio\" name=\"LED1\" value=\"1\" />ON<br>"
"<input type=\"radio\" name=\"LED1\" value=\"0\" />OFF<br />"
"</td>"
"<td>LED 2: <br />"
"<input type=\"radio\" name=\"LED2\" value=\"1\" />ON<br>"
"<input type=\"radio\" name=\"LED2\" value=\"0\" />OFF<br />"
"</td>"
"<td>LED 3: <br />"
"<input type=\"radio\" name=\"LED3\" value=\"1\" />ON<br>"
"<input type=\"radio\" name=\"LED3\" value=\"0\" />OFF<br />"
"</td>"
"</tr>"
"</table><br>"
"<input type=\"submit\" name=\"SUBMIT\"value=\"SEND\" />"
"</form>"
"<marquee><font size=\"+1\"> COMPANY: MINH HA GROUP </font></marquee><br />"
"<marquee><font size=\"+1\"> Website: BanLinhKien.Vn</font></marquee><br />"
"Copy Right MinhHaGroup<br />"
"Designed By Nguyen Quy Nhat<br />"
"</center>"
"</body>"
"</html>"
};
#endif
